### PR TITLE
when ListenUDP fails once, try again next time

### LINKED ISSUE #58: GetConnForAddr returns nil conn after ListenUDP failed

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #58.

### CODE REVIEW

File: transport.go [hunk 1]
```diff
@@ -31,26 +31,30 @@ var quicConfig = &quic.Config{
...
 		return c.connIPv4, err
 	case "udp6":
+		if c.connIPv6 != nil {
+			return c.connIPv6, nil
+		}
 		var err error
-		c.connIPv6Once.Do(func() {
-			c.connIPv6, err = c.createConn(network, ":0")
-		})
+		c.connIPv6, err = c.createConn(network, ":0")
```
Comment (anacrolix) [inline transport.go]: Why not `[::]:0`?

Comment (marten-seemann) [reply transport.go]: I'm not sure. `:0` seems to work fine. Do you see any advantage in changing this?

Comment (anacrolix) [reply transport.go]: No I was just curious. As long as "udp6" is specified, it shouldn't matter.
